//-----------------------------------------------------------------------
// <copyright file=" BiliSession.cs" company="xxxx Enterprises">
// * Copyright (C) 2021 xxxx Enterprises All Rights Reserved
// * version : 4.0.30319.42000
// * author  : auto generated by T4
// * FileName: BiliSession.cs
// * history : Created by T4 04/19/2021 14:43:37
// </copyright>
//-----------------------------------------------------------------------
using System;

namespace BiliFor.Model.Models
{
    /// <summary>
    /// BiliSession Entity Model
    /// </summary>   
    [Serializable]
    public class BiliSession
    {
        /// <summary>
        /// 
        /// </summary>
        public string uID { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string uSession { get; set; }
   
        /// <summary>
        /// 
        /// </summary>
        public string uMoney { get; set; }
    }
}
